### PR TITLE
ENTESB-2433  Move SwitchYard / BRMS Integration code into new Integratio...

### PR DESCRIPTION
**Pull request by dvirgiln**
https://issues.jboss.org/browse/ENTESB-2433

### CODE REVIEW

**Comment by chirino** [comment]
ok to test

**Comment by etirelli** [comment]
@dvirgiln @chirino Just a friendly reminder, please keep this code on master branch only. The 6.2.x branch is scheduled to be released as part of the BRMS/BPMS 6.1.0 product and it is on code freeze already. Thanks!

**Comment by chirino** [comment]
ok to test

**Comment by cunningt** [comment]
Tested and pushed the changes here.

**Pull request closed without merging**
