### PR TITLE
Cp 182

### PR DESCRIPTION
**Pull request by dvirgiln**

### CODE REVIEW

**Comment by psiroky** [comment]
My understanding was that branch 1.4.x is supposed to be for BxMS 6.3 + Fuse 6.2.1. Do we want to add the Fuse 6.3 upgrade here?

**Comment by dvirgiln** [comment]
The upgrade of fuse 6.3 version, allows the code to compile with both 6.3 and 6.2.1. 

This allows just to maintain one branch instead of 2 branches.

**Comment by psiroky** [comment]
But then we will have two identical branches - master and 1.4.x? Or am I missing something here?

**Comment by dvirgiln** [comment]
Normally on master they are included the latest changes or fixes. Not necesarily these changes needs to be released. In master we point to the last snapshot version of drools, that would be 7.0.0-SNAPSHOT. 

Master branch is never released. The 1.x branches are the branches that are released, and there are perfectus builds that build the code and release it.

**Comment by psiroky** [comment]
Thanks for the explanation. This is becoming very confusing unfortunately.

**Comment by dvirgiln** [comment]
you are welcome Petr

**Pull request merged**
