### PR TITLE
Entesb 2722

### PR DESCRIPTION
**Pull request by dvirgiln**

### CODE REVIEW

**Comment by chirino** [comment]
ok to test

**Comment by dvirgiln** [comment]
Hiram, I added the patch related the maven error downloading some artifacts. Now you would not need to include anything in your settings.xml

**Comment by chirino** [comment]
ok to test

**Comment by chirino** [comment]
ok to test

**Comment by kevinearls** [comment]
retest this please

**Comment by dvirgiln** [comment]
For testing this:

1º go into switchyard folder:
2º mvn clean install

For deploying switchyard:

EAP: mvn clean install -Prelease,eap -Deap.home=[path_to_eap]

**Comment by chirino** [comment]
Why don't we add the switchyard module as part of the root pom.xml?

**Comment by dvirgiln** [comment]
Adding it!

**Comment by cunningt** [comment]
This needs to be split into separate pulls for the separate JIRA it represents because the GAV change one will conflict with the other pull request sitting out there (https://github.com/jboss-integration/fuse-bxms-integ/pull/3)

**Pull request closed without merging**
