### PR TITLE
ENTESB-2722 Update GAV of integration project

### PR DESCRIPTION
**Pull request by cunningt**
Update GAV of integration project

### CODE REVIEW

**Comment by ge0ffrey** [comment]
+1 to merge (Edson or Mario will I presume, they asked me to look over these).

**Comment by kevinearls** [comment]
retest this please

**Comment by kevinearls** [comment]
retest this please

**Comment by dvirgiln** [comment]
Can be merged this PR?? I am waiting until it is merged to create 3 different PR for:


ENTESB-2692 fuse-bxms-integ SY module error        
ENTESB-2722 Update GAV of integration project        
ENTESB-2696 Switchyard Different behaviours depending the maven version

I've not create the PRs for avoiding conflicts with this PR.

**Comment by mariofusco** [comment]
I cannot merge this PR because it breaks all the 3 tests in org.drools.karaf.itest.KieSpringOnKarafIntegrationTest

I suspect the problem is in the features.xml file, but I am not 100% sure. Please make those tests to pass and I'll merge the PR.

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
So why are we switching to a non SNAPSHOT version?

**Comment by kevinearls** [comment]
retest this please

**Comment by cunningt** [comment]
@chirino : Don't we need to provide a ER tag for productization?   If we don't, then let's close this out and just fix the GAV issues.

**Comment by chirino** [comment]
@cunningt lets keep the master branch on SNAPSHOTS.  Once it working nicely and we are ready to build we can create a new branch/tag and update to a non-SNAPSHOT GAV.

**Comment by cunningt** [comment]
@chirino Sounds fine to me, closing this out.

**Pull request closed without merging**
